In [1]:
import numpy as np

#### Creating 2 arrays of the same shape

In [2]:
p = np.array([9,8,7])
q = np.array([3,2,4]) 

#### The + operation
The resultant array will be of the same shape as the operands with the elements in the result containing the sum of the corresponding elements in the operands.

In [3]:
p + q

array([12, 10, 11])

#### The - operation
Works much like the + operation, but computes the difference

In [4]:
p - q

array([6, 6, 3])

#### The * , / and % operations are used for multiplication, division and modulus

In [5]:
print('p * q = ', p * q)

print('p / q = ', p / q)

print('p % q = ', p % q)

p * q =  [27 16 28]
p / q =  [3.   4.   1.75]
p % q =  [0 0 3]


#### If one of the operands is a literal
The operation is performed on each element of the array operand using the literal 

In [6]:
p % 2

array([1, 0, 1])

#### Boolean operations

In [7]:
p > 8

array([ True, False, False])

In [8]:
p < 9

array([False,  True,  True])

#### Creating two 2D arrays

In [9]:
x = np.array([[2,1], [1,3]])
y = np.array([[3,2], [4,2]])

print('x: \n', x)
print('y: \n', y)

x: 
 [[2 1]
 [1 3]]
y: 
 [[3 2]
 [4 2]]


#### The + operation on 2D arrays
Much like with 1D arrays, + will result in an array with the same shape as the operands with the elements being the sum of the elements at corresponding positions in the operands.

In [10]:
x + y

array([[5, 3],
       [5, 5]])

In [11]:
x - y

array([[-1, -1],
       [-3,  1]])

In [12]:
x * y

array([[6, 2],
       [4, 6]])

#### Generate a dot product using the dot() function of an array object
This produces an array dot product. One way to generate the dot product is to call the dot() function of an array object.

In [17]:
x.dot(y)

array([[40, 24],
       [60, 32]])

#### Dot product using np.dot()
Produces a similar result as x.dot(y)

In [18]:
np.dot(x,y)

array([[40, 24],
       [60, 32]])

#### Operations using literals 
This time we modify the array x by multiplying each element by a literal value

In [19]:
x *= 4

x

array([[32, 16],
       [16, 48]])

### Aggregate operations
Start off by creating a 1D array containing the mileage of a fleet of vehicles

In [20]:
fleet_mileage = np.array([14130, 37234, 21892, 11479, 6890, 27981])

#### The sum() function
This sums up the values of the elements of the array and returns a single value

In [21]:
fleet_mileage.sum()

119606

#### The min() function
Returns the lowest value in the NumPy array

In [22]:
fleet_mileage.min()

6890

#### The max() function
Returns the highest value in the array

In [23]:
fleet_mileage.max()

37234

#### The mean() function gives the average

In [24]:
print('Mean: ', fleet_mileage.mean())

Mean:  19934.333333333332


### Aggregate operations on 2D arrays

In [25]:
num = np.arange(16).reshape(4,4)

num

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### A simple sum() function call returns a single value
This sums up the values of every single element in the array

In [26]:
num.sum()

120

#### Get the sum of individual rows or columns
Specify the axis along with the aggregate operation needs to occur. A value of 0 for the axis argument will perform the aggregation for each column and return a 1D array whose size corresponds to the number of rows.

In [27]:
num.sum(axis = 0)

array([24, 28, 32, 36])

#### Summing values of each row
Set axis=1

In [28]:
num.sum(axis = 1)

array([ 6, 22, 38, 54])

#### Axis can be set for all aggregation functions
We do so here for the min() operation

In [29]:
num.min(axis = 1)

array([ 0,  4,  8, 12])

#### Get the mean() for each row

In [30]:
num.mean(axis = 1)

array([ 1.5,  5.5,  9.5, 13.5])