In [1]:
import numpy as np

#### Create a 1-D array

In [2]:
x = np.arange(8)

#### Printing the array using the Python print() function

In [3]:
print(x)

[0 1 2 3 4 5 6 7]


#### Printing out a 2D array
An array of 1D arrays

In [4]:
y = np.arange(16).reshape(4,4)

print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### Printing out 3D arrays
This looks like an array of 2D arrays

In [5]:
z = np.arange(36).reshape(3,4,3)

print(z)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


#### Printing out large arrays
Like with Python lists, the output will contain '...' between the initial and end elements. This is an array summarization rather than a full representation

In [6]:
np.arange(12100)

array([    0,     1,     2, ..., 12097, 12098, 12099])

#### The same applies to 2D arrays

In [7]:
print(np.arange(12100).reshape(110,110))

[[    0     1     2 ...   107   108   109]
 [  110   111   112 ...   217   218   219]
 [  220   221   222 ...   327   328   329]
 ...
 [11770 11771 11772 ... 11877 11878 11879]
 [11880 11881 11882 ... 11987 11988 11989]
 [11990 11991 11992 ... 12097 12098 12099]]


#### Viewing entire array
If you would like to view the full contents of the array rather than a summarization, use the np.set_printoptions() function and set the threshold argument to null (np.nan). The threshold sets the point at which summarization of the array occurs - a value of n means that any array exceeding n elements will be summarized. The default threshold value is 1000

In [14]:
np.set_printoptions(threshold = np.nan)

ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation

In [10]:
print(np.arange(12100).reshape(110,110))

[[    0     1     2 ...   107   108   109]
 [  110   111   112 ...   217   218   219]
 [  220   221   222 ...   327   328   329]
 ...
 [11770 11771 11772 ... 11877 11878 11879]
 [11880 11881 11882 ... 11987 11988 11989]
 [11990 11991 11992 ... 12097 12098 12099]]


#### An array of 100 elements will be displayed in full by default
Since at this point the threshold is np.nan, but even by default, the threshold is 1000

In [11]:
print(np.arange(100).reshape(10,10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


#### Setting the threshold to 50 will cause this same array to be summarized

In [12]:
np.set_printoptions(threshold = 50)

print(np.arange(100).reshape(10,10))

[[ 0  1  2 ...  7  8  9]
 [10 11 12 ... 17 18 19]
 [20 21 22 ... 27 28 29]
 ...
 [70 71 72 ... 77 78 79]
 [80 81 82 ... 87 88 89]
 [90 91 92 ... 97 98 99]]
