#### Install NumPy using pip

In [1]:
!pip install numpy --upgrade

     |████████████████████████████████| 15.1MB 11.1MB/s eta 0:00:01
  Found existing installation: numpy 1.17.2
    Uninstalling numpy-1.17.2:
      Successfully uninstalled numpy-1.17.2


#### Import the NumPy library

In [2]:
import numpy as np

#### Create a NumPy array from a Python list
Use the np.array() function to initialize a NumPy array from a list

In [3]:
array_one = np.array([0,1,3,5,7,9])

array_one

array([0, 1, 3, 5, 7, 9])

#### Initializing a NumPy array from a list variable

In [4]:
num = [11,22,33,44,55,66,77]
array_two = np.array(num)
array_two

array([11, 22, 33, 44, 55, 66, 77])

#### Creating an array of zeros
One may often need to initialize an array with zeroes and later update the values of individual elements. There is an np.zeros() function to do that. It's argument is a tuple conveying the shape of the array (number of rows and columns) 

In [5]:
array_of_zeroes = np.zeros((2,3))
array_of_zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

#### Creating an array of ones
Similar to np.zeros(), there is an np.ones() function. By default the type of the elements here is a float.

In [6]:
array_of_ones = np.ones((3,2))
array_of_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
array_of_ones.dtype

dtype('float64')

#### Array of integer ones
Specify the dtype argument if you would like the elements to be of a particular type

In [8]:
array_of_ones = np.ones((3,2), dtype = np.int32)
array_of_ones

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

#### Create an array without initializing entries
The np.empty() function creates an array of the specified shape but simply allocates memory for the array elements. The contents of the array are simply whatever is in the allocated space. Such an array needs to be initialized explicitly.

In [9]:
array_empty = np.empty((3,2))
array_empty

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

#### Identity matrix using np.eye()
This returns an array which is effectively a square matrix of the specified size. The diagonal elements are 1 while the rest are 0. 

In [10]:
array_eye = np.eye(4)
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Creating an array with a specified range and interval
The np.arange() function takes in a lower bound, and upper bound and the interval for the elements in the NumPy array. 

In [11]:
array_of_evens = np.arange(2,24,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

#### The interval in a range need not be an integer

In [12]:
array_of_floats = np.arange(1, 3, 0.3)
array_of_floats

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8])

#### Creating a 2D array using np.array()
This is done using a list of tuples where each tuple represents a row in the 2D array

In [13]:
array_2D = np.array([(3,4,6),(2,1,6)])
array_2D

array([[3, 4, 6],
       [2, 1, 6]])

#### The shape property
This gives the size of the array in terms of (numRows, numColumns)

In [14]:
array_2D.shape

(2, 3)

#### Create a sequence using np.arange()

In [15]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

#### The reshape() function
This will re-order the elements of the array so that they are arranged in the specified shape

In [16]:
array_nd = np.arange(8).reshape(2,4)
array_nd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

#### The reshape() operation needs the right number of elements
The number of elements should match the product of the dimensions listed in the array shape

In [17]:
array_nd = np.arange(6).reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

#### The array_nd has a shape of (2,4)

In [18]:
array_nd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

#### Create an array of ones with the shape of an existing array
The np.ones_like() function takes as argument an existing array, and produces an array of ones matching the shape of the argument.

In [19]:
array_ones = np.ones_like(array_nd)
array_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])